USE TALLER_DEYTONA
GO

CREATE TABLE TBL_USUARIO_ACCION_AUDITORIA
(
NUM_ACCION INT IDENTITY PRIMARY KEY,
NUM_EMPLEADO INT REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
ACCION   VARCHAR(80),
FECHA    DATETIME,
MODIFICADO_POR VARCHAR(90)
)
CREATE TABLE TBL_USUARIO_ACCESO_AUDITORIA
(
NUM_ACCESO INT IDENTITY PRIMARY KEY,
NUM_EMPLEADO INT REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
ACCION   VARCHAR(80),
FECHA    DATETIME,
)
-------------TABLA REPORTE
CREATE TABLE TBL_VENTA_REPORTE
(
NUM_VENTA INT IDENTITY PRIMARY KEY,
NUM_PRODUCTO  INT ,
NUM_EMPLEADO INT REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
NUM_CLIENTE INT REFERENCES CAT_CLIENTE(NUM_CLIENTE),
FECHA    DATETIME,
TOTAL    MONEY
)
GO
----------TRIGGER INSERT REPORTE VENTA
CREATE TRIGGER TR_REPORTE_VENTA_REP
ON TBL_FACTURA_REPUESTO FOR INSERT
AS

BEGIN
SET NOCOUNT ON
DECLARE @NUM_PRODUCTO  INT, @NUM_EMPLEADO INT, @NUM_CLIENTE INT, @TOTAL   MONEY
SELECT @NUM_PRODUCTO = NUM_REPUESTO FROM inserted
SELECT @NUM_EMPLEADO = NUM_EMPLEADO FROM inserted
SELECT @NUM_CLIENTE = CLIENTE FROM inserted
SELECT @TOTAL = TOTAL FROM inserted
INSERT INTO TBL_VENTA_REPORTE VALUES(@NUM_PRODUCTO,@NUM_EMPLEADO,@NUM_CLIENTE,GETDATE(),@TOTAL)
END
GO

CREATE TRIGGER TR_REPORTE_VENTA_SERV
ON TBL_FACTURA_SERVICIO FOR INSERT
AS

BEGIN
SET NOCOUNT ON
DECLARE @NUM_PRODUCTO  INT, @NUM_EMPLEADO INT, @NUM_CLIENTE INT, @TOTAL   MONEY
SELECT @NUM_PRODUCTO = NUM_FACTURA_SERVICIO FROM inserted
SELECT @NUM_EMPLEADO = EMPLEADO FROM inserted
SELECT @NUM_CLIENTE = CLIENTE FROM inserted
SELECT @TOTAL = TOTAL FROM inserted
INSERT INTO TBL_VENTA_REPORTE VALUES(@NUM_PRODUCTO,@NUM_EMPLEADO,@NUM_CLIENTE,GETDATE(),@TOTAL)
END
GO

CREATE TRIGGER TR_REPORTE_VENTA_AUTO
ON TBL_FACTURA FOR INSERT
AS

BEGIN
SET NOCOUNT ON
DECLARE @NUM_PRODUCTO  INT, @NUM_EMPLEADO INT, @NUM_CLIENTE INT, @TOTAL   MONEY
SELECT @NUM_PRODUCTO = NUM_VEHICULO FROM inserted
SELECT @NUM_EMPLEADO = NUM_EMPLEADO FROM inserted
SELECT @NUM_CLIENTE = NUM_CLIENTE FROM inserted
SELECT @TOTAL = TOTAL FROM inserted
INSERT INTO TBL_VENTA_REPORTE VALUES(@NUM_PRODUCTO,@NUM_EMPLEADO,@NUM_CLIENTE,GETDATE(),@TOTAL)
END
GO
-------------TRIGGER DELETE REPORTE
CREATE TRIGGER TR_DELETE_VENTA_AUTO
ON TBL_FACTURA FOR DELETE
AS

BEGIN
SET NOCOUNT ON
DECLARE @NUM_PRODUCTO INT
SELECT @NUM_PRODUCTO = NUM_VEHICULO FROM inserted
DELETE FROM TBL_VENTA_REPORTE
WHERE NUM_PRODUCTO = @NUM_PRODUCTO AND ESTADO = 0 
END
GO

CREATE TRIGGER TR_DELETE_VENTA_SERV
ON TBL_FACTURA_SERVICIO FOR DELETE
AS

BEGIN
SET NOCOUNT ON
DECLARE @NUM_PRODUCTO INT
SELECT @NUM_PRODUCTO = NUM_FACTURA_SERVICIO FROM inserted
DELETE FROM TBL_VENTA_REPORTE
WHERE NUM_PRODUCTO = @NUM_PRODUCTO 
END
GO

CREATE TRIGGER TR_DELETE_VENTA_REP
ON TBL_FACTURA_REPUESTO FOR DELETE
AS

BEGIN
SET NOCOUNT ON
DECLARE @NUM_PRODUCTO INT
SELECT @NUM_PRODUCTO = NUM_REPUESTO FROM inserted
DELETE FROM TBL_VENTA_REPORTE
WHERE NUM_PRODUCTO = @NUM_PRODUCTO 
END
GO
-------------REPORTE VENTA
CREATE PROCEDURE SP_REPORTE_VENTA_DIA
@FECHA DATE 
AS
BEGIN
SELECT * FROM TBL_VENTA_REPORTE
WHERE DAY(FECHA) = DAY(@FECHA)
END
GO
CREATE PROCEDURE SP_REPORTE_VENTA_MES
@FECHA DATE 
AS
BEGIN
SELECT * FROM TBL_VENTA_REPORTE
WHERE MONTH(FECHA) = MONTH(@FECHA)
END
GO
CREATE TRIGGER TR_INSERT_TBL_USUARIO
ON TBL_USUARIO FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE @NUM_EMPLEADO INT, @MODIFICADO_POR VARCHAR(90)
SELECT @NUM_EMPLEADO  = EMPLEADO FROM inserted
INNER JOIN CAT_EMPLEADO AS E ON E.NUM_EMPLEADO = EMPLEADO
 WHERE E.NUM_EMPLEADO = EMPLEADO 
INSERT INTO TBL_USUARIO_ACCION_AUDITORIA VALUES(@NUM_EMPLEADO,'ACCION INSERSIÓN',GETDATE(),@MODIFICADO_POR)
END 

GO
----------TABLA REPORTE COMPRA
CREATE TABLE TBL_COMPRA_REPORTE
(
NUM_VENTA INT IDENTITY PRIMARY KEY,
NUM_PRODUCTO  INT ,
NUM_EMPLEADO INT REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
NUM_CLIENTE INT REFERENCES CAT_CLIENTE(NUM_CLIENTE),
FECHA    DATETIME,
TOTAL    MONEY
)
GO

CREATE TRIGGER TR_MODIF_TBL_USUARIO_AUDITORIA
ON TBL_USUARIO FOR UPDATE
AS
BEGIN
SET NOCOUNT ON
DECLARE @NUM_EMPLEADO INT, @MODIFICADO_POR VARCHAR(90)
SELECT @NUM_EMPLEADO  = EMPLEADO FROM inserted
INNER JOIN CAT_EMPLEADO AS E ON E.NUM_EMPLEADO = EMPLEADO
WHERE E.NUM_EMPLEADO = EMPLEADO
SELECT @MODIFICADO_POR = SYSTEM_USER 
INSERT INTO TBL_USUARIO_ACCION_AUDITORIA VALUES(@NUM_EMPLEADO,'ACCION MODIFICACIÓN',GETDATE(),@MODIFICADO_POR)
END 

GO
CREATE TRIGGER TR_DELETE_TBL_USUARIO_AUDITORIA
ON TBL_USUARIO FOR DELETE
AS
BEGIN
SET NOCOUNT ON
DECLARE @NUM_EMPLEADO INT, @FECHA DATETIME, @MODIFICADO_POR VARCHAR(90)
SELECT @NUM_EMPLEADO  = EMPLEADO FROM deleted
INNER JOIN CAT_EMPLEADO AS E ON E.NUM_EMPLEADO = EMPLEADO
 WHERE E.NUM_EMPLEADO = EMPLEADO
SELECT @MODIFICADO_POR = SYSTEM_USER 
INSERT INTO TBL_USUARIO_ACCION_AUDITORIA VALUES(@NUM_EMPLEADO,'ACCION BORRADO',GETDATE(),@MODIFICADO_POR)
END 

GO
CREATE PROCEDURE SP_SELECT_FECHA_TBL_USUARIO_AUDITORIA
@FECHA DATE
AS
BEGIN
SELECT * FROM TBL_USUARIO_ACCION_AUDITORIA
WHERE MONTH(FECHA) = MONTH(@FECHA)
END

GO
select * FROM TBL_USUARIO
SELECT * FROM CAT_EMPLEADO