CREATE DATABASE DEYTONA
GO
USE DEYTONA
GO

CREATE TABLE CAT_CATEGORIA(
NUM_CATEG INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NOMBRE_CATEGORIA NCHAR(40) NOT NULL,
DESCRIPCION VARCHAR(255),
)

CREATE TABLE CAT_CLIENTE(
NUM_CLIENTE INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
CEDULA CHAR(25),
GENERO CHAR(1),
FECHA_NAC DATE,
ESTAD_CIVIL CHAR(1),
DOMICILIO VARCHAR(100) NOT NULL,
TELEFONO INT,
WEB CHAR(40),
CORREO CHAR(40),
TIPO_CLIENTE INT,
NUM_VEHICULO INT
)

CREATE TABLE CAT_EMPLEADO(
NUM_EMPLEADO INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
CEDULA CHAR(25) NOT NULL,
INSS CHAR(20),
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
FECHA_NAC DATE,
CARGO INT,
GENERO CHAR(1) NOT NULL,
ESTADO_CIVIL CHAR(1) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
TELEFONO INT,
CORREO VARCHAR(70),
WEB VARCHAR(70)
--FK__CAT_EMPLEADO FOREIGN KEY (CARGO) REFERENCES TBL_CARGO(NUM_CARGO)
)

CREATE TABLE CAT_PROVEEDOR(
NUM_PROVEEDOR INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NUM_IDENTIFICACION VARCHAR(40) NOT NULL,
TIPO_PROVEEDOR INT,
NOMBRE VARCHAR(100),
APELLIDO_RAZON_SOCIAL VARCHAR(100) NOT NULL,
FECHA_CONSTITU DATE,
DIRECCION VARCHAR(100),
TELEFONO VARCHAR(30),
CORREO VARCHAR(60),
PAG_WEB VARCHAR(100),
REGIS_POR VARCHAR(70),
AUTORIZ_POR VARCHAR(70),
FECHA_INGRESO_SIST DATETIME
)

CREATE TABLE CAT_REPUESTO(
NUM_REPUESTO INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NUM_CATEGORIA INT,
NOMBRE_REP VARCHAR(30) NOT NULL,
DESCRIPCION_REP VARCHAR(100) NOT NULL,
UNIDAD_MEDIDA CHAR(10) NOT NULL,
NUM_SERIE VARCHAR(70),
COD_BARRA VARCHAR(90),
REGIST_POR VARCHAR(70),
FECHA_REGIST DATETIME
)

CREATE TABLE CAT_SERVICIO(
NUM_SERVICO INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
SERVICIO VARCHAR(20) NOT NULL,
TIPO INT,
PRECIO MONEY NOT NULL
)

CREATE TABLE TBL_CARGO(
NUM_CARGO INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
CARGO VARCHAR(30) NOT NULL
)

CREATE TABLE TBL_DETALLE_FACT_SERVICIO(
NUM_DETALLE_FAC INT IDENTITY PRIMARY KEY,
SERVICIO INT,
MECANICO INT,
FACTURA  INT
)

CREATE TABLE TBL_DETALLE_FACT_VEHICULO(
NUM_DETALLE_FACT_VEHIC INT IDENTITY PRIMARY KEY,
VEHICULO INT,
FACTURA  INT
)

CREATE TABLE TBL_DETALLE_LOTE(
NUM_DET_LOTE INT IDENTITY PRIMARY KEY,
VEHICULO INT,
LOTE     INT
)

CREATE TABLE TBL_DOCUMENTACION(
NUM_DOC INT IDENTITY PRIMARY KEY,
CARTA_COMPRA_VENTA VARCHAR(20) NOT NULL,
CIRCULACION VARCHAR(20) NOT NULL,
MATRICULA VARCHAR(10) NOT NULL
)

CREATE TABLE TBL_ENTRADA(
NUM_ENTRADA INT IDENTITY PRIMARY KEY,
NUM_DISTRIB INT,
NUM_EMPLEADO INT,
FECHA DATETIME NOT NULL,
OBSERVACIONES VARCHAR(80) NOT NULL,
SUB_TOTAL DECIMAL(18,6),
DECUENTO DECIMAL(18,6),
IMPUESTO DECIMAL(18,6),
TOTAL DECIMAL(18,6) NOT NULL
)

CREATE TABLE TBL_EQUIPO_MECANICO(
NUM_EQUIPO INT IDENTITY PRIMARY KEY,
MOTOR VARCHAR(30) NOT NULL,
CILINDROS VARCHAR(30) NOT NULL,
TIPO_TRANSMICION VARCHAR(30) NOT NULL,
TIPO_FRENOS VARCHAR(30) NOT NULL
)

CREATE TABLE TBL_FACTURA(
NUM_FACTURA INT IDENTITY PRIMARY KEY,
NUM_CLIENTE INT,
NUM_EMPLEADO INT,
FECH_FACTURA DATE,
SUB_TOTAL MONEY,
IMPUESTO DECIMAL(18,6),
TOTAL MONEY
)

CREATE TABLE TBL_INVENTARIO(
NUM_INVENTARIO INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NUM_REPUESTO INT,
CANT_MAX DECIMAL(18,6),
CANT_MIN DECIMAL(18,6),
EXISTENCIA DECIMAL(18,6),
DISPONIBILIDAD DECIMAL(18,6),
FECHA_INVENTARIO DATE
)

CREATE TABLE TBL_LOTE(
NUM_LOTE INT IDENTITY PRIMARY KEY,
EMPLEADO INT,
DISTRIBUIDOR INT,
FECHA_INGRESO DATE NOT NULL
)

CREATE TABLE TBL_MANTENIMIENTO(
NUM_MANTENIM INT IDENTITY PRIMARY KEY,
VEHICULO INT,
TIPO_MANTENIM INT,
OBSERVACIONES VARCHAR(MAX) NOT NULL,
REGISTRADO_POR INT,
FECH_MANTENIM DATETIME
)

CREATE TABLE TBL_REGISTRO_MANTENIMIENTO(
NUM_REG_MANT INT IDENTITY PRIMARY KEY,
MANTENIMIENTO INT,
FECHA_MANTEN DATETIME
)

CREATE TABLE TBL_SALIDA(
NUM_SALIDA INT IDENTITY PRIMARY KEY,
NUN_EMPLEADO INT,
FECHA DATETIME NOT NULL,
TIPO_SALIDA VARCHAR(30) NOT NULL,
OBSERVACIONES VARCHAR(80) NOT NULL,
SUB_TOTAL DECIMAL(18,6),
DESCUENTO DECIMAL(18,6),
IMPUESTO DECIMAL(18,6),
TOTAL DECIMAL(18,6)
)

CREATE TABLE TBL_TIPO_CLIENTE(
NUM_TIPO_CLI INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
DESCUENTO DECIMAL(10,2)
)

CREATE TABLE TBL_TIPO_MANTENIMIENTO(
NUM_TIPO_MANT INT IDENTITY PRIMARY KEY,
MANTENIMIENTO NCHAR(50) NOT NULL,
DESCRIPCION NCHAR(80) NOT NULL
)

CREATE TABLE TBL_TIPO_PROVEEDOR(
NUM_TIPO_PROVEEDOR INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NOMBRE CHAR(20) NOT NULL,
DESCRIPCION CHAR(80) NOT NULL
)

CREATE TABLE TBL_TIPO_SERVICIO(
NUM_TIPO_SERVIC INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
TIPO VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(80) NOT NULL
)

CREATE TABLE TBL_VEHICULO(
NUM_VEHICULO INT IDENTITY PRIMARY KEY,
NUM_DOCUMENT INT,
NUM_EQUI_MECANICO INT,
OBSERVACIONES VARCHAR(80) NOT NULL,
PRECIO_COMPRA MONEY NOT NULL,
PRECIO_VENTA MONEY NOT NULL,
ESTADO BIT NOT NULL
)

CREATE TABLE TBL_VEHICULO_CLIENTE(
NUM_VEHIC_CLIENT INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
MARCA NCHAR(30) NOT NULL,
PLACA NCHAR(20) NOT NULL,
CATEGORIA NCHAR(20) NOT NULL
)

CREATE TABLE TBL_HIST_PRECIO(
NUM_HIST_PRECIO INT IDENTITY PRIMARY KEY,
TIPO_PRODUC VARCHAR(80) NOT NULL,
CODIGO VARCHAR(30),
DESCRIPCION VARCHAR(250),
NOMBRE_PRODUCT VARCHAR(20) NOT NULL
)

CREATE TABLE TBL_USUARIO(
NUM_EMPLEADO INT IDENTITY PRIMARY KEY,
CARGO INT,
USUARIO CHAR(20) NOT NULL,
CONTRASENA BINARY(800) NOT NULL,
FECH_CUENTA DATETIME NOT NULL
)

