CREATE DATABASE TALLER_DEYTONA
GO 
USE TALLER_DEYTONA
GO


CREATE TABLE TBL_CARGO(
NUM_CARGO    INT IDENTITY PRIMARY KEY,
ESTADO     BIT NOT NULL,
CARGO  VARCHAR(30)NOT NULL
)
GO
GO
CREATE TABLE TBL_DOCUMENTACION(
NUM_DOCUMENTACION    INT IDENTITY PRIMARY KEY,
CARTA_COMPRA_VENTA  VARCHAR(20) NOT NULL,
CIRCULACION         VARCHAR(20) NOT NULL,
MATRICULA           VARCHAR(10) NOT NULL
)


CREATE TABLE TBL_EQUIPOMECANICO(
NUM_EQUIPO    INT IDENTITY PRIMARY KEY,
MOTOR        VARCHAR(30) NOT NULL,
CILINDROS    VARCHAR(30) NOT NULL,
TRANSMICION  VARCHAR(30) NOT NULL,
FRENOS       VARCHAR(30) NOT NULL
)

CREATE TABLE TBL_TIPO_MANTENIMIENTO(
ID_MANTENIMIENTO INT IDENTITY PRIMARY KEY,
MANTENIMIENTO    VARCHAR(50) NOT NULL,
DESCRIPCION      VARCHAR(80) NOT NULL
)


CREATE TABLE TBL_TIPO_CLIENTE(
IDTIPO        INT IDENTITY PRIMARY KEY,
ESTADO        BIT NOT NULL,
TIPO      VARCHAR(30) NOT NULL,
DESCUENTO FLOAT
)

CREATE TABLE TBL_TIPO_PROVEEDOR(
IDTIPOPROVEEDOR  INT IDENTITY PRIMARY KEY,
ESTADO           BIT NOT NULL,
TIPO         VARCHAR(20) NOT NULL,
DESCRIPCION  VARCHAR(80) NOT NULL
)

CREATE TABLE TBL_TIPO_SERVICIO(
NUM_SERVICIO  INT IDENTITY PRIMARY KEY,
ESTADO       BIT NOT NULL,
TIPO         VARCHAR(50) NOT NULL,
DESCRIPCION  VARCHAR(80) NOT NULL
)

CREATE TABLE TBL_VEHICULO(
NUM_VEHICULO       INT IDENTITY PRIMARY KEY,
NUM_DOCUMENTACION  INT,
NUM_EQUIPOMECANICO INT,
OBSERVACIONES      VARCHAR(30),
PRECIO_COMPRA      MONEY NOT NULL,
PRECIO_VENTA       MONEY NOT NULL,
ESTADO            BIT,
CONSTRAINT FK_TBL_VEHICULO_TBL_DOCUMENTACION FOREIGN KEY (NUM_DOCUMENTACION) REFERENCES TBL_DOCUMENTACION(NUM_DOCUMENTACION),
CONSTRAINT FK_TBL_VEHICULO_TBL_EQUIPOMECANICO FOREIGN KEY (NUM_EQUIPOMECANICO) REFERENCES TBL_EQUIPOMECANICO(NUM_EQUIPO)
)
CREATE TABLE TBL_VEHICULO_CLIENTE(
NUM_VEHICULO    INT IDENTITY PRIMARY KEY,
ESTADO        BIT NOT NULL,
MARCA     VARCHAR(30) NOT NULL,
PLACA     VARCHAR(20) NOT NULL,
CATEGORIA VARCHAR(20) NOT NULL
)


CREATE TABLE CAT_CATEGORIA(
NUM_CATEGORIA         INT IDENTITY PRIMARY KEY,
ESTADO                BIT NOT NULL,
NOMBRE_CATEGORIA  VARCHAR(40) NOT NULL,
DESCRIPCION_CATEG VARCHAR(255)
)

CREATE TABLE TBL_HISTORIAL_PRECIO(
NUM_HISTORIAL  INT IDENTITY PRIMARY KEY,
CODIGO         VARCHAR(30) NOT NULL,
PRECIO         MONEY NOT NULL,
FECHA          DATE NOT NULL,
DESCRIPCION    VARCHAR(255) NOT NULL,
NOMBRE_PRODUCTO VARCHAR(20) NOT NULL
)

CREATE TABLE CAT_CLIENTE(
NUM_CLIENTE          INT IDENTITY PRIMARY KEY,
ESTADO               BIT NOT NULL,
NOMBRE_CLIENTE   VARCHAR(40) NOT NULL,
APELLIDO_CLIENTE VARCHAR(40) NOT NULL,
CEDULA_CLIENTE   VARCHAR(25) NOT NULL,
GENERO           CHAR(1),
FECHA_NAC        DATE,
ESTADO_CIVIL     CHAR(1),
DOMICILIO        VARCHAR(100) NOT NULL,
NUM_TELEFONO         INT ,
WEB              VARCHAR(40),
CORREO           VARCHAR(40),
TIPO_CLIENTE     VARCHAR(40) NOT NULL,
VEHICULO         VARCHAR(40)
)

CREATE TABLE CAT_EMPLEADO(
NUM_EMPLEADO     INT IDENTITY PRIMARY KEY,
ESTADO           BIT NOT NULL,
NO_CEDULA        VARCHAR(25) NOT NULL,
NO_INSS          VARCHAR(20),
NOMBRE       VARCHAR(40) NOT NULL,
APELLIDO     VARCHAR(40) NOT NULL,
DAT_FECHA_NAC    DATE,
CARGO        INT NOT NULL,
GENERO       CHAR(1) NOT NULL,
ESTADO_CIVIL CHAR(1) ,
DIRECCION    VARCHAR(100),
NUM_TELEFONO     INT,
CORREO       VARCHAR(40),
WEB          VARCHAR(80),
CONSTRAINT FK_CAT_EMPLEADO_TBL_CARGO FOREIGN KEY (CARGO) REFERENCES TBL_CARGO(NUM_CARGO)
)

CREATE TABLE  TBL_MANTENIMIENTO(
NUM_MANTENIMIENTO    INT IDENTITY PRIMARY KEY,
VEHICULO             INT NOT NULL,
TIPO_MANTENIMIENTO   INT NOT NULL,
OBSERVACIONES        VARCHAR(MAX),
REGISTRADO_POR       INT NOT NULL,
FECHA_MANTENIMIENTO  DATE,
CONSTRAINT FK_TBL_MANTENIMIENTO_TBL_TIPO_MANTENIMIENTO FOREIGN KEY (TIPO_MANTENIMIENTO) REFERENCES TBL_TIPO_MANTENIMIENTO(ID_MANTENIMIENTO),
CONSTRAINT FK_TBL_MANTENIMIENTO_CAT_EMPLEADO FOREIGN KEY (REGISTRADO_POR) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
CONSTRAINT FK_TBL_MANTENIMIENTO_TBL_VEHICULO_CLIENTE FOREIGN KEY (VEHICULO) REFERENCES TBL_VEHICULO_CLIENTE(NUM_VEHICULO)
)
CREATE TABLE TBL_REGISTRO_MANTENIMIENTO(
IDREGISTROM     INT IDENTITY PRIMARY KEY,
MANTENIMIENTO   INT NOT NULL,
FECHA_DATE      DATETIME,
CONSTRAINT FK_TBL_REGISTRO_MANTENIMIENTO_TBL_MANTENIMIENTO FOREIGN KEY (MANTENIMIENTO) REFERENCES TBL_MANTENIMIENTO(NUM_MANTENIMIENTO)
)

CREATE TABLE CAT_PROVEEDOR(
NUM_PROVEEDOR               INT IDENTITY PRIMARY KEY,
ESTADO                      BIT NOT NULL,
NUM_IDENTIFICACION          VARCHAR(30),
TIPO_PROVEEDOR          INT NOT NULL ,
NOMBRE                  VARCHAR(100) NOT NULL,
APELLIDO_RAZON_SOCIAL   VARCHAR(100) NOT NULL,
FECHA_NAC_CONSTITUCION  DATETIME,
DIRECCION               VARCHAR(100),
TELEFONO                INT,
CORREO                  VARCHAR(40),
PAGWEB                  VARCHAR(100),
REGISTRADO_POR          VARCHAR(70),
AUTORIZADO_POR          VARCHAR(70),
FECHAINGRESOSISTEM      DATETIME,
CONSTRAINT FK_CAT_PROVEEDOR_TBL_TIPO_PROVEEDOR FOREIGN KEY (TIPO_PROVEEDOR) REFERENCES TBL_TIPO_PROVEEDOR(IDTIPOPROVEEDOR)
)

CREATE TABLE TBL_LOTE(
IDLOTE        INT IDENTITY PRIMARY KEY,
EMPLEADO      INT NOT NULL,
DISTRIBUIDOR  INT NOT NULL,
FECHA_INGRESO DATE NOT NULL,
CONSTRAINT FK_TBL_LOTE_CAT_EMPLEADO FOREIGN KEY (EMPLEADO) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
CONSTRAINT FK_TBL_LOTE_CAT_PROVEEDOR FOREIGN KEY (DISTRIBUIDOR) REFERENCES CAT_PROVEEDOR(NUM_PROVEEDOR)
)

CREATE TABLE CAT_REPUESTO(
NUM_REPUESTO               INT IDENTITY PRIMARY KEY,
ESTADO                     BIT NOT NULL,
NUM_CATEGORIA              INT,
NOMBRE_REPUESTO        VARCHAR(30) NOT NULL,
DESCRIPCION_REPUESTO   VARCHAR(100),
UNIDAD_MEDIDA          VARCHAR(20) NOT NULL,
NUM_SERIE              VARCHAR(70),
CODIGO_BARRA           VARCHAR(100),
PRECIO_COMPRA          DECIMAL(18,2),
REGISTRADO_POR         VARCHAR(70),
FECHA_REGISTRO         DATE,
CONSTRAINT FK_CAT_REPUESTO_CAT_CATEGORIA FOREIGN KEY (NUM_CATEGORIA) REFERENCES CAT_CATEGORIA(NUM_CATEGORIA)
)
CREATE TABLE TBL_SALIDA(
NUM_SALIDA    INT IDENTITY PRIMARY KEY,
NUM_REPUESTO  INT REFERENCES CAT_REPUESTO(NUM_REPUESTO),
NUM_EMPLEADO  INT NOT NULL,
DAT_FECHA     DATETIME NOT NULL,
TIPO_SALIDA   VARCHAR(30) NOT NULL,
OBSERVACIONES VARCHAR(80) NOT NULL,
CANTIDAD      FLOAT,
CONSTRAINT FK_TBL_SALIDA_CAT_EMPLEADO FOREIGN KEY (NUM_EMPLEADO) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO)
)

CREATE TABLE CAT_FORMA_PAGO(
NUM_PAGO INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NOMBRE VARCHAR(20)
)
CREATE TABLE CAT_MONEDA(
NUM_MONEDA INT IDENTITY PRIMARY KEY,
ESTADO BIT NOT NULL,
NOMBRE  VARCHAR(20)
)
CREATE TABLE TBL_FACTURA_REPUESTO(
NUM_FACT_REPUESTO INT IDENTITY PRIMARY KEY,
ESTADO       BIT,
NUM_REPUESTO INT NOT NULL,
DESCRIPCION_REPUESTO VARCHAR(100),
UNIDAD    DECIMAL(10,2),
NUM_EMPLEADO INT NOT NULL,
CLIENTE INT NOT NULL,
FORMA_PAGO INT NOT NULL,
MONEDA INT NOT NULL,
FECHA DATETIME NOT NULL,
CANTIDAD DECIMAL(10,2) NOT NULL,
PRECIO_UNIDAD DECIMAL(18,2) NOT NULL,
IVA  DECIMAL(10,2),
TOTAL       DECIMAL(18,2),
CONSTRAINT FK_TBL_FACTURA_REPUESTOCAT_EMPLEADO FOREIGN KEY (NUM_EMPLEADO) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
CONSTRAINT FK_TBL_FACTURA_REPUESTO_CAT_REPUESTO FOREIGN KEY (NUM_REPUESTO) REFERENCES CAT_REPUESTO(NUM_REPUESTO),
CONSTRAINT FK_TBL_FACTURA_REPUESTO_CAT_FORMA_PAGO FOREIGN KEY (FORMA_PAGO) REFERENCES CAT_FORMA_PAGO(NUM_PAGO),
CONSTRAINT FK_TBL_FACTURA_REPUESTO_CAT_MONEDA FOREIGN KEY (MONEDA) REFERENCES CAT_MONEDA(NUM_MONEDA)
)

CREATE TABLE TBL_INVENTARIO(
ID_INVENTARIO        INT IDENTITY PRIMARY KEY,
ESTADO               BIT NOT NULL,
NUM_REPUESTO         INT REFERENCES CAT_REPUESTO(NUM_REPUESTO),
CANTIDAD             FLOAT,
CANT_MIN             FLOAT,
DAT_FECHA_INVENTARIO DATE,
CONSTRAINT FK_TBL_INVENTARIO_CAT_REPUESTO  FOREIGN KEY (NUM_REPUESTO) REFERENCES CAT_REPUESTO(NUM_REPUESTO)
)

CREATE TABLE TBL_ENTRADA(
NUM_ENTRADA       INT IDENTITY PRIMARY KEY,
NUM_REPUESTO      INT, 
NUM_DISTRIBUIDOR  INT  FOREIGN KEY (NUM_DISTRIBUIDOR) REFERENCES CAT_PROVEEDOR(NUM_PROVEEDOR),
NUM_EMPLEADO      INT FOREIGN KEY (NUM_EMPLEADO) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
DAT_FECHA         DATETIME NOT NULL,
OBSERVACIONES     VARCHAR(80) NOT NULL,
CANTIDAD          FLOAT,
SUBTOTAL          FLOAT,
DESCUENTO         FLOAT,
IMPUESTO          FLOAT,
TOTAL             FLOAT NOT NULL
)
CREATE TABLE TBL_DETALLE_FACTURA_SERVICIO(
NUM_DETALLEF INT IDENTITY PRIMARY KEY,
SERVICIO     INT NOT NULL,
MECANICO     INT NOT NULL,
FACTURA      INT NOT NULL,
)

CREATE TABLE CAT_SERVICIOS(
NUM_SERVICIO INT IDENTITY PRIMARY KEY,
NUM_DETALLE_SERVICIO INT NOT NULL,
ESTADO       BIT NOT NULL,
SERVICIO     VARCHAR(20) NOT NULL,
TIPO         INT NOT NULL,
PRECIO       MONEY,
CONSTRAINT FK_CAT_SERVICIO_TBL_DETALLE_FACTURA_SERVICIO  FOREIGN KEY (NUM_DETALLE_SERVICIO) REFERENCES TBL_DETALLE_FACTURA_SERVICIO(NUM_DETALLEF),
CONSTRAINT FK_CAT_SERVICIO_TBL_SERVICIO  FOREIGN KEY (TIPO) REFERENCES TBL_TIPO_SERVICIO(NUM_SERVICIO)
)

CREATE TABLE TBL_FACTURA_SERVICIO(
NUM_FACTURA_SERVICIO INT IDENTITY PRIMARY KEY,
CLIENTE              INT REFERENCES CAT_CLIENTE(NUM_CLIENTE),
EMPLEADO             INT NOT NULL,
FECHA                DATE NOT NULL,
NUM_DETALLE_SERVICIO INT NOT NULL,
NUM_VEHICULO INT NOT NULL,
SERVICIO INT REFERENCES CAT_SERVICIOS(NUM_SERVICIO),
MONEDA   INT REFERENCES CAT_MONEDA(NUM_MONEDA),
FORMA_PAGO   INT REFERENCES CAT_FORMA_PAGO(NUM_PAGO),
CANTIDAD INT,
PRECIO MONEY NOT NULL,
IMPUESTO FLOAT,
TOTAL    MONEY,
)

CREATE TABLE TBL_PRECIO_REPUESTO(
NUM_PRECIO_REPUESTO INT IDENTITY PRIMARY KEY,
NUM_REPUESTO INT NOT NULL,
ESTADO  BIT,
FECHA   DATE,
PRECIO_COMPRA FLOAT,
IVA FLOAT,
TOTAL FLOAT,
CONSTRAINT FK_TBL_PRECIO_CAT_REPUESTO FOREIGN KEY (NUM_REPUESTO) REFERENCES CAT_REPUESTO(NUM_REPUESTO)
)

CREATE TABLE TBL_USUARIO(
NUM_USUARIO  INT IDENTITY PRIMARY KEY,
ESTADO       BIT NOT NULL,
EMPLEADO   INT NOT NULL,
USUARIO      VARCHAR(20) NOT NULL,
CONTRASENA    VARBINARY(800) NOT NULL,
FECHA_CUENTA  DATE NOT NULL,
CONSTRAINT FK_TBL_USUARIO_CAT_EMPLEADO FOREIGN KEY (EMPLEADO) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO)
)

CREATE TABLE TBL_FACTURA(
NUM_FACTURA   INT IDENTITY PRIMARY KEY,
NUM_CLIENTE   INT REFERENCES CAT_CLIENTE(NUM_CLIENTE),
NUM_EMPLEADO  INT REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
ESTADO        BIT,
FORMA_PAGO    INT REFERENCES CAT_FORMA_PAGO(NUM_PAGO),
MONEDA        INT REFERENCES CAT_MONEDA(NUM_MONEDA),
FECHA_FACTURA DATE,
CANTIDAD      FLOAT,
SUB_TOTAL     MONEY,
IMPUESTO      FLOAT,
TOTAL         MONEY,
CONSTRAINT FK_TBL_FACTURA_CAT_EMPLEADO FOREIGN KEY (NUM_EMPLEADO) REFERENCES CAT_EMPLEADO(NUM_EMPLEADO),
CONSTRAINT FK_TBL_FACTURA_CAT_CLIENTE FOREIGN KEY (NUM_CLIENTE) REFERENCES CAT_CLIENTE(NUM_CLIENTE)
)

CREATE TABLE TBL_DETALLE_FACTURA_VEHICULO(
NUM_DETALLEF INT IDENTITY PRIMARY KEY,
VEHICULO     INT,
FACTURA      INT,
CONSTRAINT FK_TBL_DETALLE_FACTURA_VEHICULO FOREIGN KEY(VEHICULO) REFERENCES TBL_VEHICULO(NUM_VEHICULO),
CONSTRAINT FK_TBL_DETALLE_FACTURA FOREIGN KEY(FACTURA) REFERENCES TBL_FACTURA(NUM_FACTURA)
)
CREATE TABLE TBL_DETALLE_LOTE(
NUMDETALLE  INT IDENTITY PRIMARY KEY,
VEHICULO    INT,
LOTE        INT,
CONSTRAINT FK_TBL_DETALLE_LOTE_VEHICULO FOREIGN KEY(VEHICULO) REFERENCES TBL_VEHICULO(NUM_VEHICULO),
CONSTRAINT FK_TBL_DETALLE_LOTE FOREIGN KEY(VEHICULO) REFERENCES TBL_LOTE(IDLOTE)
)

GO
INSERT INTO CAT_CATEGORIA VALUES(1,'NEUMATICO','NEOMATICOS DE VEHICULOS')
INSERT INTO CAT_CATEGORIA VALUES(1,'DEPORTIVO','REPUESTOS DE VEHICULOS DEPORTIVOS')

INSERT INTO TBL_TIPO_SERVICIO VALUES(1,'SUSPENSION','SUSPENSION DE VEHICULO')
INSERT INTO TBL_TIPO_SERVICIO VALUES(1,'ELECTRICIDAD AUTOMOTRIZ','TODO TIPO DE VEHICULO')

INSERT INTO TBL_TIPO_PROVEEDOR VALUES(1,'REPUESTO DE CARRO','REPUESTO DE CARROS')
INSERT INTO TBL_TIPO_PROVEEDOR VALUES(1,'LLANTAS','TODO TIPO DE VEHICULO')
INSERT INTO TBL_TIPO_PROVEEDOR VALUES(1,'AMORTIGUADORES','TODO TIPO DE VEHICULO')

INSERT INTO TBL_CARGO VALUES(1,'ADMINISTRADOR')
INSERT INTO TBL_CARGO VALUES(1,'OPERARIO')
INSERT INTO TBL_CARGO VALUES(1,'GERENTE')
INSERT INTO CAT_EMPLEADO VALUES(1,'002-060493-0004X','26655738','ERICK JAVIER','CRUZ','1993-04-06',1,'M','S','MANAGUA ESTACION 2 DE POLICIA 6 C AL ESTE',81944369,'erickcroz2013@gmail.com','')
INSERT INTO TBL_USUARIO VALUES(1,1,'user',CONVERT(varbinary(800),ENCRYPTBYPASSPHRASE('password','user')),getdate())
INSERT INTO TBL_USUARIO VALUES(1,1,'admin',CONVERT(varbinary(800),ENCRYPTBYPASSPHRASE('password','admin')),getdate())
SELECT * FROM TBL_USUARIO
--GO
--INSERT INTO CAT_EMPLEADO VALUES(1,'002-060493-0004X',77777777,'ERICK JAVIER','CRUZ','1993-04-06',1,'M','S','MANAGUA ESTACION 2 POLICIA 6 C AL OESTE 1 C NORTE',
--81944369,'erickcroz2013@gmail.com','')
--INSERT INTO TBL_USUARIO VALUES ('USUARIO'  , ENCRYPTBYPASSPHRASE('password','USUARIO')  ,@nombres ,@dni )             
--GO
--CREATE PROCEDURE SP_SESION

--@I_USUARIO AS VARCHAR(20),
--@I_CONTRASE AS VARBINARY(800)

--AS
--BEGIN

--SELECT * FROM TBL_USUARIO
--WHERE @I_USUARIO = USUARIO AND @I_CONTRASE = CONTRASENA

--END
