USE TALLER_DEYTONA
GO

CREATE TRIGGER TR_HISTORIAL_PRECIO_CAT_SERVICIO 
ON CAT_SERVICIOS FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE @CODIGO VARCHAR(30),@PRECIO MONEY,@NOMBRE_PR VARCHAR(20)
SELECT @CODIGO = NUM_SERVICIO FROM inserted
SELECT @PRECIO = PRECIO FROM inserted
SELECT @NOMBRE_PR = SERVICIO FROM inserted
INSERT INTO TBL_HISTORIAL_PRECIO VALUES(@CODIGO,@PRECIO,GETDATE(),'PRECIO SERVICIO ACTUALIZADO',@NOMBRE_PR)
END
GO

CREATE TRIGGER TR_HISTORIAL_PRECIO_CAT_REPUESTO
ON CAT_REPUESTO FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE @NUM_REPUESTO VARCHAR(30),@PRECIO_COMPRA MONEY,@DESDE DATE,@NOMBRE_PR VARCHAR(20)
SELECT @NUM_REPUESTO = NUM_REPUESTO FROM inserted
SELECT @PRECIO_COMPRA = PRECIO_COMPRA FROM inserted
SELECT @DESDE = FECHA_REGISTRO FROM inserted
SELECT @NOMBRE_PR = NOMBRE_REPUESTO FROM inserted
INSERT INTO TBL_HISTORIAL_PRECIO VALUES(@NUM_REPUESTO,@PRECIO_COMPRA,@DESDE,'PRECIO REPUESTO ACTUALIZADO',@NOMBRE_PR)
END
GO

CREATE TRIGGER TR_INSERT_DETALLE_FACTURA_SERVICIO
ON TBL_FACTURA_SERVICIO FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE @SERVICIO INT, @MECANICO INT, @FACTURA INT
SELECT @SERVICIO = SERVICIO FROM inserted
SELECT @MECANICO = EMPLEADO FROM inserted
SELECT @FACTURA = NUM_FACTURA_SERVICIO FROM inserted
INSERT INTO TBL_DETALLE_FACTURA_SERVICIO VALUES(@SERVICIO,@MECANICO,@FACTURA)
END
--CREATE TABLE TBL_HISTORIAL_PRECIO(
--CODIGO         VARCHAR(30) NOT NULL,
--PRECIO         MONEY NOT NULL,
--DESDE          DATE NOT NULL,
--HASTA          DATE NOT NULL,
--DESCRIPCION    VARCHAR(255) NOT NULL,
--NOMBRE_PRODUCTO VARCHAR(20) NOT NULL
--)