USE TALLER_DEYTONA
GO
---------------SALIDA DE INVENTARIO
CREATE TRIGGER TR_SALIDA_TBL_FACTURA_REPUESTO
ON TBL_FACTURA_REPUESTO FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE  @CANTIDAD FLOAT
SELECT @CANTIDAD = CANTIDAD FROM inserted
UPDATE  TBL_INVENTARIO SET CANTIDAD = TBL_INVENTARIO.CANTIDAD - inserted.CANTIDAD FROM inserted
WHERE TBL_INVENTARIO.NUM_REPUESTO = inserted.NUM_REPUESTO
END

GO
CREATE TRIGGER TR_SALIDA_TBL_FACTURA_REPUESTO_SALIDA
ON TBL_SALIDA FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE  @CANTIDAD FLOAT
SELECT @CANTIDAD = CANTIDAD FROM inserted
UPDATE  TBL_INVENTARIO SET CANTIDAD = TBL_INVENTARIO.CANTIDAD - inserted.CANTIDAD FROM inserted
WHERE TBL_INVENTARIO.NUM_REPUESTO = inserted.NUM_REPUESTO
END
--------ENTRADA INVENTARIO
GO
CREATE TRIGGER TR_ENTRADA_TBL_FACTURA_REPUESTO
ON TBL_ENTRADA FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE  @CANTIDAD FLOAT
SELECT @CANTIDAD = CANTIDAD FROM inserted
UPDATE  TBL_INVENTARIO SET CANTIDAD = TBL_INVENTARIO.CANTIDAD + inserted.CANTIDAD FROM inserted
WHERE TBL_INVENTARIO.NUM_REPUESTO = inserted.NUM_REPUESTO
END
--------- DETALLE FACTURA
GO
CREATE TRIGGER TR_DETALLE_TBL_FACTURA_SERVICIO
ON TBL_FACTURA_SERVICIO FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE  @SERVICIO INT, @MECANICO INT, @FACTURA INT
SELECT @SERVICIO = SERVICIO FROM inserted
SELECT @MECANICO = EMPLEADO FROM inserted
SELECT @FACTURA = NUM_FACTURA_SERVICIO FROM inserted
INSERT INTO TBL_DETALLE_FACTURA_SERVICIO VALUES(@SERVICIO,@MECANICO,@FACTURA)
END
GO
---------PRECIO REPUESTO
CREATE TRIGGER TR_PRECIO_REPUESTO
ON TBL_ENTRADA FOR INSERT
AS
BEGIN
SET NOCOUNT ON
DECLARE @NUM_REP INT,@NUM_DISTR INT,@NUM_EMPL INT,@PRECIO FLOAT
SELECT @PRECIO = SUBTOTAL FROM inserted
SELECT @NUM_REP = NUM_REPUESTO FROM inserted 
SELECT @NUM_DISTR = NUM_DISTRIBUIDOR FROM inserted
SELECT @NUM_EMPL = NUM_EMPLEADO FROM inserted
If Exists(SELECT * FROM TBL_PRECIO_REPUESTO WHERE NUM_REPUESTO = @NUM_REP)
BEGIN
UPDATE TBL_PRECIO_REPUESTO SET  
ESTADO = 1,
PRECIO_COMPRA = @PRECIO,
IVA = @PRECIO*0.15,
TOTAL = PRECIO_COMPRA+IVA
WHERE TBL_PRECIO_REPUESTO.NUM_REPUESTO = @NUM_REP
END
ELSE
BEGIN
INSERT INTO TBL_PRECIO_REPUESTO VALUES(@NUM_REP,1,GETDATE(),@PRECIO,@PRECIO*0.15,@PRECIO+@PRECIO*0.15)
END
END